USE CLINICA_VETERINARIA;
GO

--DQL

SELECT nomeVeterinario, CRMV, razaoSocial 
FROM CLINICA
RIGHT JOIN VETERINARIO
ON CLINICA.idClinica = VETERINARIO.idClinica;
GO




SELECT nomeDono, nomePet 
FROM PET
LEFT JOIN DONO
ON Pet.idDono = Dono.idDono;
GO


SELECT * FROM PET;
GO


SELECT nomeVeterinario, nomePet, nomeRaca, nomeTipoPet, nomeDono, razaoSocial
FROM ATENDIMENTO
LEFT JOIN PET
ON ATENDIMENTO.idPet = Pet.idPet
LEFT JOIN RACA
ON PET.idRaca = RACA.idRaca
LEFT JOIN TIPOPET
ON TIPOPET.idTipoPet = RACA.idTipoPet
LEFT JOIN VETERINARIO
ON ATENDIMENTO.idVeterinario = VETERINARIO.idVeterinario
LEFT JOIN DONO
ON PET.idDono = Dono.idDono
LEFT JOIN CLINICA
ON ATENDIMENTO.idClinica = CLINICA.idClinica;
GO

SELECT * FROM TIPOPET
WHERE nomeTipoPet LIKE '%o';
GO

SELECT * FROM RACA
WHERE nomeRaca Like 'S%';
GO


