CREATE DATABASE CLINICA_VETERINARIA; 
GO

USE CLINICA_VETERINARIA;
GO

CREATE TABLE CLINICA(
idClinica TINYINT PRIMARY KEY IDENTITY (1,1),
endereco VARCHAR(100),
);
GO

CREATE TABLE DONO (
idDono SMALLINT PRIMARY KEY IDENTITY (1,1),
nomeDono VARCHAR (50),
);
GO

CREATE TABLE TIPOPET (
idTipoPet INT PRIMARY KEY IDENTITY (1,1),
nomeTipoPet VARCHAR (70),
);
GO

CREATE TABLE VETERINARIO (
idVeterinario SMALLINT PRIMARY KEY IDENTITY (1,1),
nomeVeterinario VARCHAR (50),
);
GO

CREATE TABLE RACA (
idRaca SMALLINT PRIMARY KEY IDENTITY (1,1),
idTipoPet INT FOREIGN KEY REFERENCES TIPOPET (idTipoPet),
nomeRaca VARCHAR(50),
);
GO

CREATE TABLE PET (
idPet SMALLINT PRIMARY KEY IDENTITY (1,1),
nomePet VARCHAR(100),
dataNascimento DATE,
idDono SMALLINT FOREIGN KEY REFERENCES DONO (idDono),
idRaca SMALLINT FOREIGN KEY REFERENCES RACA (idRaca),
);
GO

CREATE TABLE ATENDIMENTO (
idAtendimento SMALLINT PRIMARY KEY IDENTITY (1,1),
idPet SMALLINT FOREIGN KEY REFERENCES PET (idPet),
idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO (idVeterinario),
dataAtendimento DATE,
);
GO

