CREATE DATABASE SENAI_HROADS_TARDE;
GO

USE SENAI_HROADS_TARDE;
GO

CREATE TABLE TIPOHABILIDADE (
idTipoHabilidade TINYINT PRIMARY KEY IDENTITY (1,1),
nomeTipoHabilidade VARCHAR(100) NOT NULL
);
GO

CREATE TABLE HABILIDADE (
idHabilidade SMALLINT PRIMARY KEY IDENTITY (1,1),
idTipoHabilidade TINYINT FOREIGN KEY REFERENCES tipoHabilidade (idTipoHabilidade),
nomeHabilidade VARCHAR(150),
nomeHabilidade2 VARCHAR(150)
);
GO

CREATE TABLE CLASSE (
idClasse TINYINT PRIMARY KEY IDENTITY (1,1),
idHabilidade SMALLINT FOREIGN KEY REFERENCES HABILIDADE (idHabilidade),
nomeClasse VARCHAR (100) NOT NULL
);
GO

CREATE TABLE PERSONAGEM (
idPersonagem INT PRIMARY KEY IDENTITY (1,1),
idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse),
nomePersonagem VARCHAR (200) NOT NULL,
capacidadeVidaMax SMALLINT NOT NULL,
CapacidadeManaMax TINYINT NOT NULL,
dataUtilizacao DATETIME NOT NULL,
dataCriacao DATETIME NOT NULL
);
GO